name: pollution_environment
description: Ứng dụng môi trường thông minh.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.4+124

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  animations: ^2.0.2
  dio: ^4.0.4
  google_maps_flutter: ^2.1.4
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.0
  image_picker: ^0.8.4+9
  fluttertoast: ^8.0.8
  flutter_slidable: ^1.2.0
  rxdart: ^0.27.3
  get: ^4.6.1
  flutter_launcher_icons: ^0.9.2
  flutter_easyloading: ^3.0.3
  jwt_decoder: ^2.0.1
  dropdown_search: ^3.0.1
  pull_to_refresh: ^2.0.0
  flex_color_scheme: ^7.0.5
  google_fonts: ^2.3.1
  dotted_border: ^2.0.0+2
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  firebase_messaging: ^11.2.6
  firebase_core: ^1.15.0
  flutter_local_notifications: ^9.3.2
  carousel_slider: ^4.0.0
  device_info_plus: ^3.2.2
  flutter_svg: ^1.0.3
  fl_chart: ^0.50.1
  package_info_plus: ^1.4.0
  google_maps_flutter_web: ^0.3.2+1
  share_plus: ^4.0.2
  expandable: ^5.0.1
  google_maps_cluster_manager: ^3.0.0+1
  # background_locator: ^1.6.12
  background_locator:
    git:
      url: https://github.com/Yukams/background_locator_fixed 
      #  https://github.com/caiobraga/background_locator.git
      ref: master
  overlay_support: ^1.2.1
  audioplayers: ^0.20.1
  workmanager: ^0.4.1
  modal_bottom_sheet: ^2.0.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  equatable: ^2.0.3
  flutter_speed_dial: ^5.1.0
  shared_preferences: ^2.0.13
  home_widget: ^0.1.5
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  wave: ^0.2.0
  geolocator_android: ^3.1.5
  # firebase_analytics: ^9.1.2
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  flutter_native_splash: ^2.1.6
  build_runner: ^2.1.10
  hive_generator: ^1.1.2
  flutter_lints: ^1.0.4
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logos/
     - assets/images/
     - assets/icons/
     - assets/icons/ic_pin_air.png
     - assets/icons/ic_pin_land.png
     - assets/icons/ic_pin_sound.png
     - assets/icons/ic_pin_water.png
     - assets/sound_alert.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #     - family: Lexend
  #       fonts:
  #        - asset: assets/fonts/lexend_regular.ttf
  #        - asset: assets/fonts/lexend_bold.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  remove_alpha_ios: false

flutter_native_splash:
  background_image: assets/logos/splash.png
  # branding: assets/logos/save_the_earth.png
  # branding_mode: bottom
  # android_gravity: fill
  # ios_content_mode: fill
  web_image_mode: cover
  web: true

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true
  
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) 
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'